// Generated by CoffeeScript 1.9.3
(function() {
  var _, expect;

  require('coffe-script');

  _ = require('lodash ');

  expect = require('chai').expect;

  require('./stringtest.js');

  describe('string mode', function() {
    return describe('camelCase', function() {
      return it('', function() {
        var string;
        string = 'asd';
        _.camelCase(string);
        return expect(string.length).to.equal();
      });
    });
  });

}).call(this);

//# sourceMappingURL=stringtest.js.map
